/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class enlace_DsSysJava */

#ifndef _Included_enlace_DsSysJava
#define _Included_enlace_DsSysJava
#ifdef __cplusplus
extern "C" {
#endif
#undef enlace_DsSysJava_SIZEINT
#define enlace_DsSysJava_SIZEINT 4L
#undef enlace_DsSysJava_SIZELONG
#define enlace_DsSysJava_SIZELONG 4L
#undef enlace_DsSysJava_SIZESHORT
#define enlace_DsSysJava_SIZESHORT 2L
#undef enlace_DsSysJava_SIZEgrid_filtro
#define enlace_DsSysJava_SIZEgrid_filtro 916L
#undef enlace_DsSysJava_IDOK
#define enlace_DsSysJava_IDOK 1L
#undef enlace_DsSysJava_IDCANCEL
#define enlace_DsSysJava_IDCANCEL 2L
#undef enlace_DsSysJava_IDABORT
#define enlace_DsSysJava_IDABORT 3L
#undef enlace_DsSysJava_IDRETRY
#define enlace_DsSysJava_IDRETRY 4L
#undef enlace_DsSysJava_IDIGNORE
#define enlace_DsSysJava_IDIGNORE 5L
#undef enlace_DsSysJava_IDYES
#define enlace_DsSysJava_IDYES 6L
#undef enlace_DsSysJava_IDNO
#define enlace_DsSysJava_IDNO 7L
#undef enlace_DsSysJava_IDCLOSE
#define enlace_DsSysJava_IDCLOSE 8L
#undef enlace_DsSysJava_IDHELP
#define enlace_DsSysJava_IDHELP 9L
#undef enlace_DsSysJava_MAXMENUA
#define enlace_DsSysJava_MAXMENUA 15L
#undef enlace_DsSysJava_MID_XNOTECLAS
#define enlace_DsSysJava_MID_XNOTECLAS 1000L
#undef enlace_DsSysJava_MID_MENUSG
#define enlace_DsSysJava_MID_MENUSG 1000L
#undef enlace_DsSysJava_MID_DISENO
#define enlace_DsSysJava_MID_DISENO 1100L
#undef enlace_DsSysJava_MID_XPRIMERA
#define enlace_DsSysJava_MID_XPRIMERA 8000L
#undef enlace_DsSysJava_MID_XOPCION1
#define enlace_DsSysJava_MID_XOPCION1 18001L
#undef enlace_DsSysJava_MID_XARXA
#define enlace_DsSysJava_MID_XARXA 28567L
#undef enlace_DsSysJava_DESPACHO_OMENU
#define enlace_DsSysJava_DESPACHO_OMENU 4001L
#undef enlace_DsSysJava_DESPACHO_EMENU
#define enlace_DsSysJava_DESPACHO_EMENU 4002L
#undef enlace_DsSysJava_DESPACHO_PANTALLAS
#define enlace_DsSysJava_DESPACHO_PANTALLAS 4003L
#undef enlace_DsSysJava_DESPACHO_TITULO
#define enlace_DsSysJava_DESPACHO_TITULO 4004L
#undef enlace_DsSysJava_DESPACHO_MAINCOMMAND
#define enlace_DsSysJava_DESPACHO_MAINCOMMAND 4005L
#undef enlace_DsSysJava_NUEVA_TECLA_PROGRAMADA
#define enlace_DsSysJava_NUEVA_TECLA_PROGRAMADA 4006L
#undef enlace_DsSysJava_DESPACHO_EN_LINEAS
#define enlace_DsSysJava_DESPACHO_EN_LINEAS 4007L
#undef enlace_DsSysJava_DESPACHO_MI_CONTROL
#define enlace_DsSysJava_DESPACHO_MI_CONTROL 4008L
#undef enlace_DsSysJava_DESPACHO_FIN_CONTROL
#define enlace_DsSysJava_DESPACHO_FIN_CONTROL 4009L
#undef enlace_DsSysJava_DESPACHO_PRE_CONTROL
#define enlace_DsSysJava_DESPACHO_PRE_CONTROL 4010L
#undef enlace_DsSysJava_DESPACHO_SOBRE_PANTALLA
#define enlace_DsSysJava_DESPACHO_SOBRE_PANTALLA 4011L
#undef enlace_DsSysJava_DESPACHO_REPON_PANTALLA
#define enlace_DsSysJava_DESPACHO_REPON_PANTALLA 4012L
#undef enlace_DsSysJava_DESPACHO_MENSAJE_CABECERA
#define enlace_DsSysJava_DESPACHO_MENSAJE_CABECERA 4013L
#undef enlace_DsSysJava_DESPACHO_FUNCIONES_IMPRESION
#define enlace_DsSysJava_DESPACHO_FUNCIONES_IMPRESION 4014L
#undef enlace_DsSysJava_DESPACHO_BOTONSALIDA
#define enlace_DsSysJava_DESPACHO_BOTONSALIDA 4015L
#undef enlace_DsSysJava_DESPACHO_COMMANDCONTROL
#define enlace_DsSysJava_DESPACHO_COMMANDCONTROL 4016L
#undef enlace_DsSysJava_DESPACHO_TRASMISION
#define enlace_DsSysJava_DESPACHO_TRASMISION 4017L
#undef enlace_DsSysJava_DESPACHO_PROGRESO
#define enlace_DsSysJava_DESPACHO_PROGRESO 4018L
#undef enlace_DsSysJava_DESPACHO_USUARIOS
#define enlace_DsSysJava_DESPACHO_USUARIOS 4019L
#undef enlace_DsSysJava_DESPACHO_INICIO_TRAZA
#define enlace_DsSysJava_DESPACHO_INICIO_TRAZA 4020L
#undef enlace_DsSysJava_DESPACHO_FIN_TRAZA
#define enlace_DsSysJava_DESPACHO_FIN_TRAZA 4021L
#undef enlace_DsSysJava_DESPACHO_PUNTO_TRAZA
#define enlace_DsSysJava_DESPACHO_PUNTO_TRAZA 4022L
#undef enlace_DsSysJava_DESPACHO_BINARIO
#define enlace_DsSysJava_DESPACHO_BINARIO 4023L
#undef enlace_DsSysJava_DESPACHO_PROCESAMENSAJES
#define enlace_DsSysJava_DESPACHO_PROCESAMENSAJES 4024L
#undef enlace_DsSysJava_DESPACHO_CCONTROL
#define enlace_DsSysJava_DESPACHO_CCONTROL 4025L
#undef enlace_DsSysJava_DESPACHO_CEDIT
#define enlace_DsSysJava_DESPACHO_CEDIT 4026L
#undef enlace_DsSysJava_DESPACHO_GETDATACONTROL
#define enlace_DsSysJava_DESPACHO_GETDATACONTROL 4027L
#undef enlace_DsSysJava_DESPACHO_FOCOCONTROL
#define enlace_DsSysJava_DESPACHO_FOCOCONTROL 4028L
#undef enlace_DsSysJava_DESPACHO_DESTRUYECONTROL
#define enlace_DsSysJava_DESPACHO_DESTRUYECONTROL 4029L
#undef enlace_DsSysJava_DESPACHO_REFRESCACONTROL
#define enlace_DsSysJava_DESPACHO_REFRESCACONTROL 4030L
#undef enlace_DsSysJava_DESPACHO_FOCOWINDOW
#define enlace_DsSysJava_DESPACHO_FOCOWINDOW 4031L
#undef enlace_DsSysJava_DESPACHO_TRAEFICHERO
#define enlace_DsSysJava_DESPACHO_TRAEFICHERO 4032L
#undef enlace_DsSysJava_DESPACHO_ENLACEWORD
#define enlace_DsSysJava_DESPACHO_ENLACEWORD 4033L
#undef enlace_DsSysJava_DESPACHO_LISTADO
#define enlace_DsSysJava_DESPACHO_LISTADO 4034L
#undef enlace_DsSysJava_DESPACHO_BROWSE
#define enlace_DsSysJava_DESPACHO_BROWSE 4035L
#undef enlace_DsSysJava_DESPACHO_ESTADOCONTROL
#define enlace_DsSysJava_DESPACHO_ESTADOCONTROL 4036L
#undef enlace_DsSysJava_DESPACHO_EURO
#define enlace_DsSysJava_DESPACHO_EURO 4037L
#undef enlace_DsSysJava_DESPACHO_SUPERUSUARIO
#define enlace_DsSysJava_DESPACHO_SUPERUSUARIO 4038L
#undef enlace_DsSysJava_DESPACHO_MENUITEM
#define enlace_DsSysJava_DESPACHO_MENUITEM 4039L
#undef enlace_DsSysJava_DESPACHO_CONSULTA_REMOTA
#define enlace_DsSysJava_DESPACHO_CONSULTA_REMOTA 4040L
#undef enlace_DsSysJava_DESPACHO_MULTIPLE
#define enlace_DsSysJava_DESPACHO_MULTIPLE 4041L
#undef enlace_DsSysJava_DESPACHO_DIF_CCONTROL
#define enlace_DsSysJava_DESPACHO_DIF_CCONTROL 4042L
#undef enlace_DsSysJava_DESPACHO_DIF_CEDIT
#define enlace_DsSysJava_DESPACHO_DIF_CEDIT 4043L
#undef enlace_DsSysJava_DESPACHO_DIF_FOCOCONTROL
#define enlace_DsSysJava_DESPACHO_DIF_FOCOCONTROL 4044L
#undef enlace_DsSysJava_DESPACHO_DATA_PROCESAMENSAJES
#define enlace_DsSysJava_DESPACHO_DATA_PROCESAMENSAJES 4045L
#undef enlace_DsSysJava_DESPACHO_DATA_INFO
#define enlace_DsSysJava_DESPACHO_DATA_INFO 4046L
#undef enlace_DsSysJava_DESPACHO9_OMENU
#define enlace_DsSysJava_DESPACHO9_OMENU 4501L
#undef enlace_DsSysJava_DESPACHO9_EMENU
#define enlace_DsSysJava_DESPACHO9_EMENU 4502L
#undef enlace_DsSysJava_DESPACHO9_PANTALLAS
#define enlace_DsSysJava_DESPACHO9_PANTALLAS 4503L
#undef enlace_DsSysJava_DESPACHO9_TITULO
#define enlace_DsSysJava_DESPACHO9_TITULO 4504L
#undef enlace_DsSysJava_DESPACHO9_QUEPANTALLA
#define enlace_DsSysJava_DESPACHO9_QUEPANTALLA 4505L
#undef enlace_DsSysJava_NUEVA9_TECLA_PROGRAMADA
#define enlace_DsSysJava_NUEVA9_TECLA_PROGRAMADA 4506L
#undef enlace_DsSysJava_DESPACHO9_EN_LINEAS
#define enlace_DsSysJava_DESPACHO9_EN_LINEAS 4507L
#undef enlace_DsSysJava_DESPACHO9_MI_CONTROL
#define enlace_DsSysJava_DESPACHO9_MI_CONTROL 4508L
#undef enlace_DsSysJava_DESPACHO9_FIN_CONTROL
#define enlace_DsSysJava_DESPACHO9_FIN_CONTROL 4509L
#undef enlace_DsSysJava_DESPACHO9_PRE_CONTROL
#define enlace_DsSysJava_DESPACHO9_PRE_CONTROL 4510L
#undef enlace_DsSysJava_DESPACHO9_SOBRE_PANTALLA
#define enlace_DsSysJava_DESPACHO9_SOBRE_PANTALLA 4511L
#undef enlace_DsSysJava_DESPACHO9_REPON_PANTALLA
#define enlace_DsSysJava_DESPACHO9_REPON_PANTALLA 4512L
#undef enlace_DsSysJava_DESPACHO9_MENSAJE_CABECERA
#define enlace_DsSysJava_DESPACHO9_MENSAJE_CABECERA 4513L
#undef enlace_DsSysJava_DESPACHO9_FUNCIONES_IMPRESION
#define enlace_DsSysJava_DESPACHO9_FUNCIONES_IMPRESION 4514L
#undef enlace_DsSysJava_DESPACHO9_HAZ_VISIBLE
#define enlace_DsSysJava_DESPACHO9_HAZ_VISIBLE 4515L
#undef enlace_DsSysJava_DESPACHO9_EDITA
#define enlace_DsSysJava_DESPACHO9_EDITA 4516L
#undef enlace_DsSysJava_DESPACHO9_TRASMISION
#define enlace_DsSysJava_DESPACHO9_TRASMISION 4517L
#undef enlace_DsSysJava_DESPACHO9_PROGRESO
#define enlace_DsSysJava_DESPACHO9_PROGRESO 4518L
#undef enlace_DsSysJava_DESPACHO9_USUARIOS
#define enlace_DsSysJava_DESPACHO9_USUARIOS 4519L
#undef enlace_DsSysJava_DESPACHO9_INICIO_TRAZA
#define enlace_DsSysJava_DESPACHO9_INICIO_TRAZA 4520L
#undef enlace_DsSysJava_DESPACHO9_FIN_TRAZA
#define enlace_DsSysJava_DESPACHO9_FIN_TRAZA 4521L
#undef enlace_DsSysJava_DESPACHO9_PUNTO_TRAZA
#define enlace_DsSysJava_DESPACHO9_PUNTO_TRAZA 4522L
#undef enlace_DsSysJava_DESPACHO9_BINARIO
#define enlace_DsSysJava_DESPACHO9_BINARIO 4523L
#undef enlace_DsSysJava_DESPACHO9_PRETRANSLATE
#define enlace_DsSysJava_DESPACHO9_PRETRANSLATE 4524L
#undef enlace_DsSysJava_DESPACHO9_TRAEFICHERO
#define enlace_DsSysJava_DESPACHO9_TRAEFICHERO 4532L
#undef enlace_DsSysJava_DESPACHO9_ENLACEWORD
#define enlace_DsSysJava_DESPACHO9_ENLACEWORD 4533L
#undef enlace_DsSysJava_DESPACHO9_BROWSE
#define enlace_DsSysJava_DESPACHO9_BROWSE 4535L
#undef enlace_DsSysJava_DESPACHO9_ESTADOCONTROL
#define enlace_DsSysJava_DESPACHO9_ESTADOCONTROL 4536L
#undef enlace_DsSysJava_DESPACHO9_EURO
#define enlace_DsSysJava_DESPACHO9_EURO 4537L
#undef enlace_DsSysJava_DESPACHO9_SUPERUSUARIO
#define enlace_DsSysJava_DESPACHO9_SUPERUSUARIO 4538L
#undef enlace_DsSysJava_ID_RECORD_UPDATE
#define enlace_DsSysJava_ID_RECORD_UPDATE 32828L
#undef enlace_DsSysJava_ID_RECORD_NEW
#define enlace_DsSysJava_ID_RECORD_NEW 32829L
#undef enlace_DsSysJava_ID_RECORD_DELETE
#define enlace_DsSysJava_ID_RECORD_DELETE 32830L
#undef enlace_DsSysJava_ID_RECORD_FIRST
#define enlace_DsSysJava_ID_RECORD_FIRST 59648L
#undef enlace_DsSysJava_ID_RECORD_LAST
#define enlace_DsSysJava_ID_RECORD_LAST 59649L
#undef enlace_DsSysJava_ID_RECORD_NEXT
#define enlace_DsSysJava_ID_RECORD_NEXT 59650L
#undef enlace_DsSysJava_ID_RECORD_PREV
#define enlace_DsSysJava_ID_RECORD_PREV 59651L
#undef enlace_DsSysJava_ID_SIONO
#define enlace_DsSysJava_ID_SIONO 32831L
#undef enlace_DsSysJava_ID_SIONOCANCELAR
#define enlace_DsSysJava_ID_SIONOCANCELAR 32832L
#undef enlace_DsSysJava_ID_MESSAGEBOX
#define enlace_DsSysJava_ID_MESSAGEBOX 32833L
#undef enlace_DsSysJava_ID_PREGUCLAVE
#define enlace_DsSysJava_ID_PREGUCLAVE 32834L
#undef enlace_DsSysJava_ID_ERRORFICHERO
#define enlace_DsSysJava_ID_ERRORFICHERO 32835L
#undef enlace_DsSysJava_ID_DLGKACTIVA
#define enlace_DsSysJava_ID_DLGKACTIVA 32836L
#undef enlace_DsSysJava_ID_DLGINDICES
#define enlace_DsSysJava_ID_DLGINDICES 32837L
#undef enlace_DsSysJava_ID_PTECS
#define enlace_DsSysJava_ID_PTECS 32845L
#undef enlace_DsSysJava_ID_CUSTOM_ESTADO
#define enlace_DsSysJava_ID_CUSTOM_ESTADO 32861L
#undef enlace_DsSysJava_ID_COMMANDCONTROL
#define enlace_DsSysJava_ID_COMMANDCONTROL 32862L
#undef enlace_DsSysJava_ID_TICSCON
#define enlace_DsSysJava_ID_TICSCON 32896L
#undef enlace_DsSysJava_ID_AVISOGLOBO
#define enlace_DsSysJava_ID_AVISOGLOBO 32897L
#undef enlace_DsSysJava_ID_PESTANA
#define enlace_DsSysJava_ID_PESTANA 32913L
#undef enlace_DsSysJava_DISPARO_CONTROL
#define enlace_DsSysJava_DISPARO_CONTROL 63200L
#undef enlace_DsSysJava_MAX_DISPARO_CONTROL
#define enlace_DsSysJava_MAX_DISPARO_CONTROL 63600L
#undef enlace_DsSysJava_PREDISPARO_CONTROL
#define enlace_DsSysJava_PREDISPARO_CONTROL 63600L
#undef enlace_DsSysJava_PREMAX_DISPARO_CONTROL
#define enlace_DsSysJava_PREMAX_DISPARO_CONTROL 64000L
#undef enlace_DsSysJava_BUSCA_PTECS
#define enlace_DsSysJava_BUSCA_PTECS 64000L
#undef enlace_DsSysJava_PIDO_TRASMISION
#define enlace_DsSysJava_PIDO_TRASMISION 64001L
#undef enlace_DsSysJava_PIDO_USUARIOS
#define enlace_DsSysJava_PIDO_USUARIOS 64002L
#undef enlace_DsSysJava_PIDO_EMPRESA
#define enlace_DsSysJava_PIDO_EMPRESA 64003L
#undef enlace_DsSysJava_TECLA_PING
#define enlace_DsSysJava_TECLA_PING 64004L
#undef enlace_DsSysJava_TECLA_COMBO
#define enlace_DsSysJava_TECLA_COMBO 64005L
#undef enlace_DsSysJava_TECLA_SUPERUSUARIO
#define enlace_DsSysJava_TECLA_SUPERUSUARIO 64006L
#undef enlace_DsSysJava_PIDO_VEREURO
#define enlace_DsSysJava_PIDO_VEREURO 64007L
#undef enlace_DsSysJava_PIDO_SUPERBLOQUEO
#define enlace_DsSysJava_PIDO_SUPERBLOQUEO 64008L
#undef enlace_DsSysJava_PIDO_SUPERDESBLOQUEO
#define enlace_DsSysJava_PIDO_SUPERDESBLOQUEO 64009L
#undef enlace_DsSysJava_PIDO_SUPERCAMBIO
#define enlace_DsSysJava_PIDO_SUPERCAMBIO 64010L
#undef enlace_DsSysJava_PIDO_SUPERTODO
#define enlace_DsSysJava_PIDO_SUPERTODO 64011L
#undef enlace_DsSysJava_PIDO_SUPERDESTODO
#define enlace_DsSysJava_PIDO_SUPERDESTODO 64012L
#undef enlace_DsSysJava_TECLA_CHECK
#define enlace_DsSysJava_TECLA_CHECK 64013L
#undef enlace_DsSysJava_TECLA_DOBLECLICK
#define enlace_DsSysJava_TECLA_DOBLECLICK 64014L
#undef enlace_DsSysJava_ID_BUSCON
#define enlace_DsSysJava_ID_BUSCON 64015L
#undef enlace_DsSysJava_ID_ACTIVAR_ERP
#define enlace_DsSysJava_ID_ACTIVAR_ERP 64016L
#undef enlace_DsSysJava_ID_ACTIVAR_EVT
#define enlace_DsSysJava_ID_ACTIVAR_EVT 64017L
#undef enlace_DsSysJava_TECLA_HINT
#define enlace_DsSysJava_TECLA_HINT 64018L
#undef enlace_DsSysJava_ID_ACTIVAR_EVTPBX
#define enlace_DsSysJava_ID_ACTIVAR_EVTPBX 64019L
#undef enlace_DsSysJava_ID_ACTIVAR_EVTCRM
#define enlace_DsSysJava_ID_ACTIVAR_EVTCRM 64020L
#undef enlace_DsSysJava_ID_SIGUIENTEPANE
#define enlace_DsSysJava_ID_SIGUIENTEPANE 32846L
#undef enlace_DsSysJava_ID_ANTERIORPANE
#define enlace_DsSysJava_ID_ANTERIORPANE 32847L
/*
 * Class:     enlace_DsSysJava
 * Method:    fPreInicializa
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_enlace_DsSysJava_fPreInicializa
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     enlace_DsSysJava
 * Method:    fInicializa
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_enlace_DsSysJava_fInicializa
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     enlace_DsSysJava
 * Method:    fFinaliza
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_enlace_DsSysJava_fFinaliza
  (JNIEnv *, jobject);

/*
 * Class:     enlace_DsSysJava
 * Method:    fLogin
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_enlace_DsSysJava_fLogin
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     enlace_DsSysJava
 * Method:    fOpcion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_enlace_DsSysJava_fOpcion
  (JNIEnv *, jobject);

/*
 * Class:     enlace_DsSysJava
 * Method:    fLogout
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_enlace_DsSysJava_fLogout
  (JNIEnv *, jobject);

/*
 * Class:     enlace_DsSysJava
 * Method:    fDevuelveVentana
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_enlace_DsSysJava_fDevuelveVentana
  (JNIEnv *, jobject);

/*
 * Class:     enlace_DsSysJava
 * Method:    fNuevaVentana
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_enlace_DsSysJava_fNuevaVentana
  (JNIEnv *, jobject);

/*
 * Class:     enlace_DsSysJava
 * Method:    fPreparaEjecucion
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_enlace_DsSysJava_fPreparaEjecucion
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     enlace_DsSysJava
 * Method:    fAsignaVentana
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_enlace_DsSysJava_fAsignaVentana
  (JNIEnv *, jobject);

/*
 * Class:     enlace_DsSysJava
 * Method:    fDespachadorInterno
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_enlace_DsSysJava_fDespachadorInterno
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     enlace_DsSysJava
 * Method:    fenhebra
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_enlace_DsSysJava_fenhebra
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     enlace_DsSysJava
 * Method:    memset
 * Signature: ([BIIII)V
 */
JNIEXPORT void JNICALL Java_enlace_DsSysJava_memset
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
